-- (b)
SELECT * FROM CUSTOMER 
AS C WHERE C.CUSTOMERNO IN (SELECT O.CUSTOMERNO FROM CUST_ORDER 
AS O GROUP BY O.CUSTOMERNO HAVING COUNT(O.ORDERNO) > 3);

-- (c)
SELECT * FROM ITEM 
AS I WHERE I.UNIT_PRICE < (SELECT AVG(UNIT_PRICE) FROM ITEM);

-- (d)
SELECT ORDERNO, SUM(QTY) FROM ORDER_ITEM GROUP BY ORDERNO;

-- (e)
SELECT * FROM ITEM 
WHERE ITEMNO IN (SELECT ITEMNO FROM ORDER_ITEM 
GROUP BY ITEMNO HAVING COUNT(ITEMNO) >= (SELECT (COUNT(*)/4) FROM CUST_ORDER));

SET SQL_SAFE_UPDATES =0;

-- (f)
UPDATE CUST_ORDER SET ORD_AMT = (SELECT SUM(O.QTY * I.UNIT_PRICE) FROM ORDER_ITEM 
AS O, ITEM AS I WHERE CUST_ORDER.ORDERNO = O.ORDERNO AND O.ITEMNO= I.ITEMNO);

-- (g)
CREATE VIEW CUSTOMER_DETAILS AS SELECT 
C.CUSTOMERNO,C.CNAME,COUNT(ORDERNO) AS ORDER_C FROM CUSTOMER AS C,CUST_ORDER AS O 
WHERE C.CUSTOMERNO=O.CUSTOMERNO GROUP BY C.CUSTOMERNO,C.CNAME;
